version: '3.3'
networks:
  default:

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
       - .env
    depends_on:
      - db

  migration:
    build: .
    command: python manage.py migrate
    env_file:
      - .env
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=communication
    ports:
      - 15432:5432

volumes:
  postgres_data:
